//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC_HW2_Comment.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASP_MVC_HW2_Comment.App_LocalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в.
        /// </summary>
        public static string AtTime {
            get {
                return ResourceManager.GetString("AtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Манько Николай.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бластойз.
        /// </summary>
        public static string Blastoise {
            get {
                return ResourceManager.GetString("Blastoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бульбазавр.
        /// </summary>
        public static string Bulbasaur {
            get {
                return ResourceManager.GetString("Bulbasaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чаризард.
        /// </summary>
        public static string Charizard {
            get {
                return ResourceManager.GetString("Charizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чармандер.
        /// </summary>
        public static string Charmander {
            get {
                return ResourceManager.GetString("Charmander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чармилеон.
        /// </summary>
        public static string Charmeleon {
            get {
                return ResourceManager.GetString("Charmeleon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментировать.
        /// </summary>
        public static string CommentBtnComment {
            get {
                return ResourceManager.GetString("CommentBtnComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете оставить комментарий так как данные не являются валидными.
        /// </summary>
        public static string CommentDataNotValid {
            get {
                return ResourceManager.GetString("CommentDataNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставить комментарий.
        /// </summary>
        public static string CommentLabelCommentOn {
            get {
                return ResourceManager.GetString("CommentLabelCommentOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string CommentLabelComments {
            get {
                return ResourceManager.GetString("CommentLabelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст сообщения.
        /// </summary>
        public static string CommentTextMessage {
            get {
                return ResourceManager.GetString("CommentTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все права защищены.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to русский.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время создания.
        /// </summary>
        public static string DateTimeCreation {
            get {
                return ResourceManager.GetString("DateTimeCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите ввод пароля.
        /// </summary>
        public static string EnterConfirmPassword {
            get {
                return ResourceManager.GetString("EnterConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите адрес электронной почты.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите фамилию.
        /// </summary>
        public static string EnterLastName {
            get {
                return ResourceManager.GetString("EnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин.
        /// </summary>
        public static string EnterLogin {
            get {
                return ResourceManager.GetString("EnterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст комментария.
        /// </summary>
        public static string EnterTextMessage {
            get {
                return ResourceManager.GetString("EnterTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oшибка 403 – доступ запрещен!.
        /// </summary>
        public static string Forbidden403 {
            get {
                return ResourceManager.GetString("Forbidden403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что такое ошибка 403 – доступ запрещен?
        ///Ошибка доступа 403 происходит, когда веб-страница (или другой ресурс), которую вы пытаетесь открыть в веб-браузере, является ресурсом, к которому у вас ограничен доступ.
        ///Она называется ошибкой 403 по коду состояния протокола HTTP, который использует веб-сервер для описания ошибки такого рода.
        ///Обычно это случается по одной из двух причин. Первая заключается в том, что владельцы веб-сервера осознанно установили ограничения доступа и вам действительно запрещен доступ  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Forbidden403Text {
            get {
                return ResourceManager.GetString("Forbidden403Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гастли.
        /// </summary>
        public static string Gastly {
            get {
                return ResourceManager.GetString("Gastly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генгар.
        /// </summary>
        public static string Gengar {
            get {
                return ResourceManager.GetString("Gengar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гротл.
        /// </summary>
        public static string Grotle {
            get {
                return ResourceManager.GetString("Grotle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хонтер.
        /// </summary>
        public static string Haunter {
            get {
                return ResourceManager.GetString("Haunter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к комментариям.
        /// </summary>
        public static string IndexBtnGoToComment {
            get {
                return ResourceManager.GetString("IndexBtnGoToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Покемо́н» (яп. ポケットモンスター покэтто монсута: англ. Pokémon, от англ. Pocket Monster — «карманный монстр»).
        /// </summary>
        public static string IndexText1 {
            get {
                return ResourceManager.GetString("IndexText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покемон.
        /// </summary>
        public static string IndexText10 {
            get {
                return ResourceManager.GetString("IndexText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имеет огненный тип, то, скорее всего, он будет уязвим при контакте с водным существом..
        /// </summary>
        public static string IndexText11 {
            get {
                return ResourceManager.GetString("IndexText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы игра.
        /// </summary>
        public static string IndexText12 {
            get {
                return ResourceManager.GetString("IndexText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to была не только интересной, но также и имела некоторый баланс, помимо общих характеристик разработчиками были внесены и дополнительные параметры существа. У каждого Покемона есть жизни, скорость, а также атака и защита, которые разделяются на обычную и особую. Виды Покемонов могут сильно отличаться по всем этим параметрам. Если первый Покемон не может особо похвастаться ими, то по мере того, как увеличивается редкость существ, их характеристики растут. Особенно, когда они эволюционируют. Иными словами, такая [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexText13 {
            get {
                return ResourceManager.GetString("IndexText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бульбаза́вр (яп. フシギダネ Фусигиданэ, англ. Bulbasaur).
        /// </summary>
        public static string IndexText14 {
            get {
                return ResourceManager.GetString("IndexText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вместе с Чармандером и Сквиртлом один из стартовых покемонов региона Канто. Его типы — травяной и ядовитый. На спине у него растёт крупная зелёная луковица: когда Бульбазавр появляется на свет, у него на спине есть зерно, которое позже в неё вырастает. Луковица позволяет Бульбазавру фотосинтезировать, и поэтому этот покемон любит проводить много времени на солнце..
        /// </summary>
        public static string IndexText15 {
            get {
                return ResourceManager.GetString("IndexText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чарманде́р (яп. ヒトカゲ Хитокагэ, англ. Charmander).
        /// </summary>
        public static string IndexText16 {
            get {
                return ResourceManager.GetString("IndexText16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to огненный покемон-ящерица, вместе со Сквиртлом и Бульбазавром является стартовым покемоном региона Канто. На кончике хвоста Чармандера горит пламя, по которому можно узнать его самочувствие и настроение. Если пламя у него на хвосте погаснет, то Чармандер может погибнуть. Чармандер предпочитает тёплые места, когда начинается дождь, он старается закрыть пламя у него на хвосте от дождя..
        /// </summary>
        public static string IndexText17 {
            get {
                return ResourceManager.GetString("IndexText17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сквиртл (яп. ゼニガメ Дзэнигамэ, англ. Squirtle).
        /// </summary>
        public static string IndexText18 {
            get {
                return ResourceManager.GetString("IndexText18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to водный покемон-черепаха, как и Чармандер и Бульбазавр, стартовый покемон региона Канто. В случае опасности Сквиртл прячется в панцирь, мягкий при рождении покемона, но вскоре затвердевающий. Панцирь Сквиртла предназначен не только для защиты: его обтекаемая форма позволяет покемону быстрее плавать в воде. Сквиртл способен производить по противнику мощные и точные выстрелы водой изо рта..
        /// </summary>
        public static string IndexText19 {
            get {
                return ResourceManager.GetString("IndexText19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to популярная медиафраншиза, созданная Сатоси Тадзири в 1996 году. Товарный знак «Покемон» принадлежит Nintendo, одной из крупнейших фирм-разработчиков видеоигр. «Покемон» впервые появился как пара игр, разработанных студией Game Freak, и после этого стал второй в мире по популярности серией компьютерных игр, уступив лишь другой серии игр Nintendo, Mario.
        ///Само слово «покемон» обозначает существо, обладающее сверхъестественными способностями. На данный момент существует 802 разновидности покемонов. В вымышленн [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IndexText2 {
            get {
                return ResourceManager.GetString("IndexText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пикачу́ (яп. ピカチュウ Пикатю:, англ. Pikachu).
        /// </summary>
        public static string IndexText20 {
            get {
                return ResourceManager.GetString("IndexText20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to покемон-мышь электрического типа, самый узнаваемый покемон, талисман серии, в последние годы ставший иконой японской поп-культуры. Пикачу способен высвобождать электрическую энергию, запасённую у него за щёчками, сила удара сравнима с молнией. Если собирается группа Пикачу, то их совместная энергия может вызвать грозу. Пикачу используют электричество, чтобы поджаривать ягоды и употреблять их в пищу. Этот покемон достаточно своевольный и не любит ограничений, поэтому многие тренеры держат их вне покеболов..
        /// </summary>
        public static string IndexText21 {
            get {
                return ResourceManager.GetString("IndexText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ма́чоп (яп. ワンリキー Ванкири:, англ. Machop).
        /// </summary>
        public static string IndexText22 {
            get {
                return ResourceManager.GetString("IndexText22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to покемон боевого типа. Обитает в горах, далеко от цивилизации. Он обожает тренировки и обладает талантом к боевым искусствам. Несмотря на свой невысокий рост, обладает большой физической силой: он способен поднять тяжесть, которую может поднять сотня взрослых мужчин. Мачоп может коротать время, качая мышцы с помощью валуна, но он может остаться недовольным результатом, даже если тренировался весь день..
        /// </summary>
        public static string IndexText23 {
            get {
                return ResourceManager.GetString("IndexText23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Га́стли (яп. ゴース Го:су, англ. Gastly).
        /// </summary>
        public static string IndexText24 {
            get {
                return ResourceManager.GetString("IndexText24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to покемон призрачного и ядовитого типа. Тело Гастли состоит почти полностью из газа: он способен обволакивать противника и незаметно погружать его в сон. Живёт, как правило, в старых заброшенных домах. Будучи газообразным, может проникнуть почти куда угодно, но при этом его легко сдувает ветром..
        /// </summary>
        public static string IndexText25 {
            get {
                return ResourceManager.GetString("IndexText25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тортвиг (англ. Turtwig).
        /// </summary>
        public static string IndexText26 {
            get {
                return ResourceManager.GetString("IndexText26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to покемон травяного типа из четвёртого поколения покемонов. &quot;Панцирь&quot; сделан из почвы, и покемон, обычно, живёт вблизи воды, чтобы почва была всегда влажная. Однако, в отличие от черепахи, этот покемон очень подвижен, может быстро бегать и прыгать. На голове покемона находится веточка с двумя листочками, с помощью которых он получает энергию посредством фотосинтеза..
        /// </summary>
        public static string IndexText27 {
            get {
                return ResourceManager.GetString("IndexText27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Само слово.
        /// </summary>
        public static string IndexText3 {
            get {
                return ResourceManager.GetString("IndexText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «покемон».
        /// </summary>
        public static string IndexText4 {
            get {
                return ResourceManager.GetString("IndexText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обозначает существо, обладающее сверхъестественными способностями. На данный момент существует 802 разновидности покемонов. В вымышленной истории «Покемона» люди, называющиеся тренерами покемонов, обучают их для сражений с покемонами других тренеров. Бои проходят до момента, пока один из покемонов не падает без сознания или его тренер не сдаётся, — до смерти схватки не происходят никогда. Как правило, сильные и опытные тренеры покемонов пользуются уважением..
        /// </summary>
        public static string IndexText5 {
            get {
                return ResourceManager.GetString("IndexText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы также сможете отследить развитие Покемона. Эволюция чаще всего имеет три стадии, однако иногда существо может и вовсе не развиваться. Помните, что одинаковые Покемоны могут иметь разные характеристики. Уровни Покемонов влияют на их рейтинг параметров, а также определяют, сколько атаки у них будет. Как правило, редкие Покемоны – это более сильные существа..
        /// </summary>
        public static string IndexText6 {
            get {
                return ResourceManager.GetString("IndexText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Но даже самые сильные.
        /// </summary>
        public static string IndexText7 {
            get {
                return ResourceManager.GetString("IndexText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покемоны.
        /// </summary>
        public static string IndexText8 {
            get {
                return ResourceManager.GetString("IndexText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имеют какие-то слабости. К примеру, если.
        /// </summary>
        public static string IndexText9 {
            get {
                return ResourceManager.GetString("IndexText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ивизавр.
        /// </summary>
        public static string Ivysaur {
            get {
                return ResourceManager.GetString("Ivysaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string LabelLogin {
            get {
                return ResourceManager.GetString("LabelLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginBtnSubmit {
            get {
                return ResourceManager.GetString("LoginBtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мачамп.
        /// </summary>
        public static string Machamp {
            get {
                return ResourceManager.GetString("Machamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мачоук.
        /// </summary>
        public static string Machoke {
            get {
                return ResourceManager.GetString("Machoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мачоп.
        /// </summary>
        public static string Machop {
            get {
                return ResourceManager.GetString("Machop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string NavBtnLogin {
            get {
                return ResourceManager.GetString("NavBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string NavBtnLogout {
            get {
                return ResourceManager.GetString("NavBtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string NavBtnRegistration {
            get {
                return ResourceManager.GetString("NavBtnRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string NavItemMain {
            get {
                return ResourceManager.GetString("NavItemMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string NavLabelUser {
            get {
                return ResourceManager.GetString("NavLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 404. Ресурс не найден!.
        /// </summary>
        public static string NotFound404 {
            get {
                return ResourceManager.GetString("NotFound404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка 404 означает, что пользователь перешел на страницу, где на данный момент отсутствует нужный текст и какой-либо контент. Несуществующая страница могла быть здесь раньше, возможно, ее удалили, переместили в другую категорию или подкорректировали название, в результате чего изменился URL..
        /// </summary>
        public static string NotFound404Text {
            get {
                return ResourceManager.GetString("NotFound404Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не зарегистрирован.
        /// </summary>
        public static string NotRegistered {
            get {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пичу.
        /// </summary>
        public static string Pichu {
            get {
                return ResourceManager.GetString("Pichu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пикачу.
        /// </summary>
        public static string Pikachu {
            get {
                return ResourceManager.GetString("Pikachu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Райчу.
        /// </summary>
        public static string Raichu {
            get {
                return ResourceManager.GetString("Raichu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegistrationBtnSubmit {
            get {
                return ResourceManager.GetString("RegistrationBtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegistrationHeader {
            get {
                return ResourceManager.GetString("RegistrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string RegistrationLabelConfirmPassword {
            get {
                return ResourceManager.GetString("RegistrationLabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string RegistrationLabelEmail {
            get {
                return ResourceManager.GetString("RegistrationLabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string RegistrationLabelName {
            get {
                return ResourceManager.GetString("RegistrationLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string RegistrationLabelSurname {
            get {
                return ResourceManager.GetString("RegistrationLabelSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сквиртл.
        /// </summary>
        public static string Squirtle {
            get {
                return ResourceManager.GetString("Squirtle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы были успешно зарегистрированы. Используйте свой логин и пароль для входа на сайт..
        /// </summary>
        public static string SuccessfullyRegistered {
            get {
                return ResourceManager.GetString("SuccessfullyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тортерра.
        /// </summary>
        public static string Torterra {
            get {
                return ResourceManager.GetString("Torterra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Туртвиг.
        /// </summary>
        public static string Turtwig {
            get {
                return ResourceManager.GetString("Turtwig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин должен состоять из трех букв, знака подчеркивания и трех цифр.
        /// </summary>
        public static string ValidateLogin {
            get {
                return ResourceManager.GetString("ValidateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество символов должно быть в пределах от 2 до 30.
        /// </summary>
        public static string ValidateStringLengthFirstName {
            get {
                return ResourceManager.GetString("ValidateStringLengthFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество символов должно быть в пределах от 2 до 30.
        /// </summary>
        public static string ValidateStringLengthLastName {
            get {
                return ResourceManager.GetString("ValidateStringLengthLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество символов должно быть в пределах от 6 до 10.
        /// </summary>
        public static string ValidateStringLengthPassword {
            get {
                return ResourceManager.GetString("ValidateStringLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество символов должно быть в пределах от 2 до 300.
        /// </summary>
        public static string ValidateStringLengthTextMessage {
            get {
                return ResourceManager.GetString("ValidateStringLengthTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Венузавр.
        /// </summary>
        public static string Venusaur {
            get {
                return ResourceManager.GetString("Venusaur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартортл.
        /// </summary>
        public static string Wartortle {
            get {
                return ResourceManager.GetString("Wartortle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный логин или пароль.
        /// </summary>
        public static string WrongLoginPassword {
            get {
                return ResourceManager.GetString("WrongLoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете оставить комментарий так как пользователь.
        /// </summary>
        public static string СanNotLeaveComment {
            get {
                return ResourceManager.GetString("СanNotLeaveComment", resourceCulture);
            }
        }
    }
}
